# 1D

In [1]:
import numpy as np
l1=[1,2,3,4]
arr1=np.array(l1)
arr1

array([1, 2, 3, 4])

In [7]:
arr1.ndim # Number of Dimensions

1

In [6]:
arr1.shape # number of rows and number of cols

(4,)

In [8]:
arr1.size # number of elements

4

In [25]:
arr1[0]

np.int64(1)

# 2D

In [11]:
l1=[10,20,30,40]
l2=[1,2,3,4]
#np.array(object,dtype)
np.array(l1,l2) # here l1==> object , l2==> dtype

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [13]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[l1,l2]
#np.array(object,dtype)
arr2= np.array(l) # l==> object
arr2

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [14]:
arr2.shape

(2, 4)

In [15]:
arr2.ndim

2

In [16]:
arr2.size

8

In [26]:
arr2[0][0]

np.int64(10)

In [27]:
arr2[0,0]

np.int64(10)

# 3D

In [18]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=[100,200,300,400]
l=[l1,l2,l3]
#np.array(object,dtype)
arr3= np.array(l) # l==> object
arr3

array([[ 10,  20,  30,  40],
       [  1,   2,   3,   4],
       [100, 200, 300, 400]])

In [29]:
print("Size: ",arr3.size)
print("shape: ",arr3.shape)
print("dimesion: ",arr3.ndim)

Size:  12
shape:  (3, 4)
dimesion:  2


In [23]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
l=[l1,l2,l3]
#np.array(object,dtype)
arr4= np.array(l) # l==> object
arr4

array([['10', '20', '30', '40'],
       ['1', '2', '3', '4'],
       ['A', 'B', 'C', 'D']], dtype='<U21')

In [30]:
print("Size: ",arr4.size)
print("shape: ",arr4.shape)
print("dimension: ",arr4.ndim)

Size:  12
shape:  (3, 4)
dimension:  2


In [32]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
l=[[l1,l2,l3]]
#np.array(object,dtype)
arr5= np.array(l) # l==> object
arr5

array([[['10', '20', '30', '40'],
        ['1', '2', '3', '4'],
        ['A', 'B', 'C', 'D']]], dtype='<U21')

In [33]:
print("Size: ",arr5.size)
print("shape: ",arr5.shape)
print("dimension: ",arr5.ndim)

Size:  12
shape:  (1, 3, 4)
dimension:  3


# 4D

In [51]:
import numpy as np
l1=[1,2,3,4]
l = [[[l1]]]
arr1=np.array(l)
arr1

array([[[[1, 2, 3, 4]]]])

In [52]:
print("Size: ",arr1.size)
print("shape: ",arr1.shape)
print("dimension: ",arr1.ndim)

Size:  4
shape:  (1, 1, 1, 4)
dimension:  4


In [53]:
import numpy as np
l1=[[[[1,2,3,4]]]]
arr1=np.array(l1)
arr1

array([[[[1, 2, 3, 4]]]])

In [54]:
print("Size: ",arr1.size)
print("shape: ",arr1.shape)
print("dimension: ",arr1.ndim)

Size:  4
shape:  (1, 1, 1, 4)
dimension:  4


In [43]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l=[[[l1,l2]]]
arr2= np.array(l) 
arr2

array([[[[10, 20, 30, 40],
         [ 1,  2,  3,  4]]]])

In [44]:
print("Size: ",arr2.size)
print("shape: ",arr2.shape)
print("dimension: ",arr2.ndim)

Size:  8
shape:  (1, 1, 2, 4)
dimension:  4


In [47]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
l4=['AB','BC','CD','DE']
l=[[[l1,l2,l3,l4]]]
arr6= np.array(l) 
arr6

array([[[['10', '20', '30', '40'],
         ['1', '2', '3', '4'],
         ['A', 'B', 'C', 'D'],
         ['AB', 'BC', 'CD', 'DE']]]], dtype='<U21')

In [48]:
print("Size: ",arr6.size)
print("shape: ",arr6.shape)
print("dimension: ",arr6.ndim)

Size:  16
shape:  (1, 1, 4, 4)
dimension:  4


In [55]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
l=[[[l1,l2,l3,l3]]]
arr6= np.array(l) 
arr6

array([[[['10', '20', '30', '40'],
         ['1', '2', '3', '4'],
         ['A', 'B', 'C', 'D'],
         ['A', 'B', 'C', 'D']]]], dtype='<U21')

In [56]:
print("Size: ",arr6.size)
print("shape: ",arr6.shape)
print("dimension: ",arr6.ndim)

Size:  16
shape:  (1, 1, 4, 4)
dimension:  4


In [57]:
l1=[10,20,30,40]
l2=[1,2,3,4]
l3=['A','B','C','D']
l=[[[l1,l2,l3]]]
arr6= np.array(l) 
arr6

array([[[['10', '20', '30', '40'],
         ['1', '2', '3', '4'],
         ['A', 'B', 'C', 'D']]]], dtype='<U21')

In [58]:
print("Size: ",arr6.size)
print("shape: ",arr6.shape)
print("dimension: ",arr6.ndim)

Size:  12
shape:  (1, 1, 3, 4)
dimension:  4


In [61]:
l=[1,2,3]
A=[l,l]
B=[A,A,A]
arr=np.array(B)
arr

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [62]:
arr.shape

(3, 2, 3)

In [63]:
#2,4
l=[1,2,3,4]
a=[l,l]
arr=np.array(a)
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [64]:
arr.shape

(2, 4)

In [65]:
#3,3,4
l=[1,2,3,4]
a=[l,l,l]
b=[a,a,a]
arr=np.array(b)
arr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [66]:
arr.shape

(3, 3, 4)

In [70]:
#4,3,2,2
l=[1,2]
a=[l,l]
b=[a,a,a]
c=[b,b,b,b]
arr=np.array(c)
arr

array([[[[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]]],


       [[[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]]],


       [[[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]]],


       [[[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2]]]])

In [71]:
arr.shape

(4, 3, 2, 2)

In [72]:
#5,4,3,2,1
l=[1]
a=[l,l]
b=[a,a,a]
c=[b,b,b,b]
d=[c,c,c,c,c]
arr=np.array(d)
arr

array([[[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]],



       [[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]],



       [[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
 

In [73]:
arr.shape

(5, 4, 3, 2, 1)